### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by jangorecki** [yihui/litedown#12]
Hi Yihui,
Thanks for working on this package. Do you have any estimates when it may be available on CRAN?
I would like to link it from my coming talk and CRAN link would be preferred.

**Comment by yihui** [comment]
Actually I attempted to make a CRAN release last month a few hours before heading to the hospital to welcome my newborn. The reviewer nitpicked about a few minor issues and wouldn't let it pass. I have been worn out since the arrival of the baby, and have little energy left to make a re-submission. I can perhaps retry next week. When is your talk?

**Comment by jangorecki** [comment]
Congratulation then!
No hurry, we have plenty of time. November.

**Comment by yihui** [comment]
I see. Indeed there's plenty of time for you, and this package must have been released long before your talk. I'll be using litedown for a 4-hour workshop this Friday and give a talk next week, so I definitely feel the urgency to make the first CRAN release :)

**Comment by yihui** [comment]
It finally passed the review and is on CRAN now: https://cran.r-project.org/package=litedown
