### ISSUE TITLE
[feature request] Support Typst pdf

### ISSUE THREAD

**Issue by AlexZHENGH** [yihui/litedown#21]
Since litedown is a minimalist version of RMarkdown, how about considering Typst as an alternative to LaTeX? 

LaTeX is powerful but can be overly complicated—kind of like C++. Typst might not fully replace LaTeX yet, but it’s faster to render and easier to learn and debug. Given that litedown seems to focus on HTML with PDF as a secondary option (as shown in the [one-page HTML book](https://yihui.org/litedown/)), adding Typst support could be a nice addition.

**Comment by yihui** [comment]
Thanks for the suggestion! I need to learn more about Typst to be sure, but I guess it's unlikely that I'll support it in **litedown**. I have been a believer in HTML, and would like to treat PDF as a by-product, since HTML has so many advantages over PDF. Recently I've spent a week on implementing a simple and minimal HTML fragmentation script (in JavaScript), and personally I'm quite happy with what I was able to achieve with only 180 lines of JS code. You can open https://yihui.org/litedown/ and press `p` on your keyboard to see an example (you can print to PDF using your web browser).

The rendering speed of Typst is indeed very impressive, and [**litedown** is not bad](https://mastodon.social/@hrbrmstr/112523725823023850), either :) If your Rmd document doesn't contain time-consuming code, normally the rendering would be finished within one second. If you do have code that is time-consuming to run, **litedown**'s new caching system can help too.

**Comment by AlexZHENGH** [comment]
Thanks, Yihui. I understand now.

I’ve also been reflecting on how much human effort has gone into reimplementing similar features, like rendering and layout engines for formats like PDF, HTML, and others. Then, additional layers of abstraction are often created to bridge these implementations. A lot of work is required to maintain these codes.

At the same time, books have a structured format that helps us process lengthy and complex texts by focusing on one page, section, or chapter at a time. This “batch” style of reading seems to make content more digestible. **litedown** merges the best aspects of both HTML and PDFs. Salute, and keep up the great work!

By the way, I noticed a page segmentation bug in your book, which I’ve reported in issue #25. You might want to take a look.
