### ISSUE TITLE
`roam()` cleanup

### ISSUE THREAD

**Issue by TimTaylor** [yihui/litedown#36]
I guess this is similar to #16. After previewing a file with `roam()` some resources are left behind in the `xxx__files` directory. Should these be cleaned up?

**Comment by yihui** [comment]
The tricky thing is that I don't want to accidentally clean up the `__files` directory that should have been kept. I always feel nervous about deleting files in the user directory (which is why it took a while for me to solve #16---I need to be very careful).

One possible way to solve this problem is to generate plots in `tempdir()`, where it may be safer to delete files. I'll think more about it.

**Comment by yihui** [comment]
Done. See documentation at https://github.com/yihui/litedown/commit/36e14f7b98e870fe11e3868ad1bcc84eed8312e5#diff-5dade8f7a155b8e53ca140393295504fde29ed4f02a0ab5ab79379143496e5e4
