### ISSUE TITLE
Bump xfun version dep?

### ISSUE THREAD

**Issue by TimTaylor** [yihui/litedown#41]
Unsure if you like to use patch/dev versions in the DESCRIPTION but do you want to bump the xfun version dependency? Currently the  docs from https://github.com/yihui/litedown/commit/1dd823d05e96ba35cf977ca111e3353e13c48de2 won't render with `0.49` (current min) but will with with `0.49.7` (current main).

**Comment by yihui** [comment]
The dev version is only required for the docs at the moment, which is why I mentioned that **xfun** needs to be installed from r-universe at https://github.com/yihui/litedown/issues/8#issuecomment-2496932841 (I'll make it clearer in docs).

I'll bump version in DESCRIPTION after the next CRAN release of **xfun**. Thanks!
